---
dist: trusty
sudo: required
language: node_js
node_js: "4.4"
before_install:
  - ./scripts/setEnv.sh
before_script:
  - npm install grunt-cli -g
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - ./canvas_modules/common-canvas/build.sh
  - ./canvas_modules/harness/build.sh
  - "cd ./canvas_modules/harness"
  - npm start &
  - sleep 2m # give time for test harness to start
  - npm test 
after_success:
deploy:
  - provider: script
    skip_cleanup: true
    script: ./scripts/publish_modules.sh
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: ./scripts/publish_modules.sh
    on:
      branch: release
notifications:
  slack:
    rooms:
      - watsondataplatform:XVNawCZULSfgMLsovgn2Stkp#wdp-canvas-builds
group: bluezone
