---
branches:
  only:
    - master
    - release
language: node_js
node_js: "4.4"
before_install:
  - printf "registry=https://npm-registry.whitewater.ibm.com/\n//npm-registry.whitewater.ibm.com/:_authToken=${PRIVATE_NPM_TOKEN}" > .npmrc
  - cp .npmrc ./canvas_modules/common-canvas/
  - cp .npmrc ./canvas_modules/common-properties/
  - cp .npmrc ./canvas_modules/harness/
before_script:
  - npm install grunt-cli -g
#  - export NODE_ENV=production
script:
  - ./canvas_modules/common-canvas/build.sh
  - ./canvas_modules/common-properties/build.sh
  - ./canvas_modules/harness/build.sh
before_deploy:
  - npm install @dap/dap-deploy
deploy:
#  - provider: script
#    skip_cleanup: true
#    script: ./node_modules/@dap/dap-deploy/scripts/deploy.sh -a api.stage1.ng.bluemix.net -o MokshaCanvasShaper -s dev -d common-canvas-dev.stage1.mybluemix.net -p ./scripts/deploy/deploy.properties
#    on:
#      branch: master
  - provider: script
    skip_cleanup: true
    script: ./scripts/publish_modules.sh
    on:
      branch: release
notifications:
  slack:
    rooms:
      - ibm-cloudplatform:Z9veqAF1gkr7PunL4BC83icO#wml-canvas-builds
group: bluezone
