options:
  formatter: stylish
files:
  include: '**/*.s+(a|c)ss'
  ignore: './src/**/_sprites.scss'
rules:
  no-css-comments: 0
  no-color-literals: 0
  hex-length: 0
  no-ids: 0
  no-qualifying-elements: 0
  force-pseudo-nesting: 0
  force-element-nesting: 0
  force-attribute-nesting: 0
  single-line-per-selector: 0
  class-name-format: 0
  property-sort-order: 0
  no-duplicate-properties:
    - 1
    -
      exclude:
        - background
  no-vendor-prefixes:
    - 1
    -
      'excluded-identifiers':
        - 'webkit'
        - 'moz'
  indentation:
    - 2
    -
      size: 4
  quotes:
    - 2
    -
      style: double
  hex-notation:
    - 2
    -
      style: uppercase
